---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml

driver:
  name: docker

platforms:
  - name: ansible-role-php-versions-ubuntu-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        php_version: "7.0"
        php_enable_webserver: false
